version: '3'
services:
  postgresql:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - '/opt/docker/volumes/projeto_django/postgresql:/var/lib/postgresql/data'
  django:
    depends_on:
      - postgresql
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8000:8000'
