# Generated by Django 3.2.4 on 2021-06-27 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_auto_20210627_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_refeita',
            field=models.ImageField(default='', upload_to='uploads/receitas/%y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 27, 20, 16, 0, 29082)),
        ),
    ]
