# Generated by Django 3.2.4 on 2021-06-28 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_auto_20210627_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 27, 21, 8, 12, 77088)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto_refeita',
            field=models.ImageField(upload_to='uploads/receitas/'),
        ),
    ]
